sudo: false
language: node_js
node_js:
  - '8'
before_install:
  - npm install -g codecov
before_script:
  - npm run build
script:
  - npm run test
  - npm run test:bs
after_success:
  - codecov
after_failure:
  - codecov
env:
  global:
    - secure: LERc0NHcdaO+KfVPZSecbdoh4e3ceSXM0z2AbNyhN7qhy3pvZM1Nt7pSB3oz0krV6an2RWNfuIBVXTnnhkwft4adsvGb36AGADVhglgS/htc3scv/Bw81fWTcwE2hhL8bSmZ7gettaXRi0UxGcBtZFu7unLFyO+odtkxYU+w+zuKNSVPtE55N7PbNPLsVf0L5h4iReEpZGcjFoXHxnMF4ZrBaRYuiYUIqduKkp8EyOPDX7jFuhxPXBTnbnpTXXuujzMnyqQoeN3LoFYmTGg+NoQWfoLxtLgu3DxJX9G2v7DBLNrbpAxS9u59i0SxtbbAcgqMu/zNct9lSkcFVxLGg4jqkLggHrRyF+8kgVD/uSJ0mH5zv4fZqtwQumILtSnCFtDpZASDW20PtWv7FxrWUyVZUEig9H0TfvWUCZOAl83CJ2+55y/T+jc6Jb1ELx4fl3lCTK9cu1fz1ZqMSLgRxH0EqiHuGiu+Mqtq7kkzgcCZz+JDTdqY4jlEHvX3RkFV6BoBU5BhohUzRBxCklPLZ94Zj/T6BTp68CdgLI4YdRSvwoPX4lIrTEV+4M5NHmY8qD186NDnaPReTBjCb1rhTbn5d2/3E/O0IyX6brId6gLrxCBQHgRcR1A13GoPNq0ZiUkiXY//YYKjIJK4pAJl5VrOGLnEKgnW8X2kWwA1kOk=
    - secure: AoQ1lAlRSYUGOgreY2L+FQPBqRTj1VUURPssYEPjEH1e+V8bGUu0nDYBQwvGB2U+jiGMwAwAEAUfTPpvimcn1tPyFihxOQfOGOVSKvFxpZh+fY0p1hueFakY2bZVDbV5QCAnefHSOhYgKoGZkceuQarZE/wh/DFD95uSqptDXrxWiRRheUH/TBy1ce8B1xi2/PSydxVC2WBekzNsRJrjGZcwvXF3XmhzYuUMsWqtUKeMAa2gTudS1xqxbvnXLGyQIX9Qd+Qu9Mo5cQ/0VetFgl3+ptrqEsmQtM6XxkQZvFM7LJClqd4BaP8LDFTyhh6rpIgyIDRnZlYUY5MVGqiS8NkK3li0CxtAyR/wHw0jBgFSXCOUwAYJ9len7MZ4tIQ5AWW/0MfNnzqwobmNx8R4Hm1hqUTYy0wxjessOpIAJ2emSnJ5gxmvVAtX7WdnumCc2Q+P09nyaGZl5rfRxwswPbidDZaMFgnsLkRrZ4dz4Seu46jqvdk3XfjSkoYWt5eHLW8v1WFzf9NWzzDAnxqG1VdGrc1UuWSOv9EDRhzCI/atjiW/yf+egli8HQ+hohVi1I+cvxJ7DkBAYAna/7QMHGeyEot0jIsgQfPqiYaU7Mg+P0qRRwsbj/JdgsXPGrf4ioyVsDaUrkLf5KPiweoYdKAxyKk0Z/DF2OY+REREOeM=
addons:
  chrome: stable
